### ISSUE TITLE
How to host in my own server 

### ISSUE THREAD

**Issue by alochym01** [google/peoplemath#12]

**Comment by amdw** [comment]
I'm going to assume the question here is what it would take to run PeopleMath as a production application on a private server, rather than on [Google App Engine](https://cloud.google.com/appengine/), which is what the README instructions tell you how to do.

This should certainly be possible, but it would require some more work, probably including some changes to the application.

Firstly, you'll need to decide what persistent storage mechanism you're going to use for your data. The current backend (in the [backend folder](https://github.com/google/peoplemath/tree/master/backend)) supports only [Google Cloud Datastore](https://cloud.google.com/datastore/), so assuming that won't be available to you in your environment, you'll need to write a new implementation of the Go `StorageService` interface for your chosen data store.

Then, you'll either need to add command-line parameters to `main.go` that allow you to select and configure that data store (similar to what `--inmemstore` does now), or add a new Go binary that starts the backend server using your storage service.

Then, you'll need to write configuration for whatever web server you're going to use, to achieve the same thing as the App Engine [app.yaml](https://github.com/google/peoplemath/blob/master/backend/app.yaml) file, i.e. `/api/*` and `/improve` requests should be proxied to your backend, requests for the Angular assets (HTML, JavaScript, CSS etc) should be served from a static location, and all other URLs should just serve `index.html`.

I'd be happy to accept a pull request along these lines, provided the data store and web server you intend to use are reasonably mainstream (please read [CONTRIBUTING.md](https://github.com/google/peoplemath/blob/master/CONTRIBUTING.md) first). If you're going to do this, please add a section to the README describing how to deploy in your chosen environment.

It's also important that the README's existing instructions for deploying on Google App Engine remain correct.

I hope this helped!

**Comment by amdw** [comment]
Closing this issue as I believe the question is answered.

If you'd like to contribute backend code for a specific persistent storage mechanism, and/or configuration and instructions for a specific web server, please feel free to open issues specific to those features. Many thanks!
