### ISSUE TITLE
Get rid of 'Server' struct 

### ISSUE THREAD

**Issue by vavilen84** [google/peoplemath#46]
For now this entity contains store and defaultTimeout. defaultTimeout - I suggest to put it in "storage" package. StorageService can be placed globally as a variable in "storage" package. This improvement should give us "low-coupling", because storage and REST API actions are different abstractions in a programm.

Reply from @amdw 
I'm open to suggestions on this, but I'm not generally a big fan of global variables. The fact that StorageService is behind an interface is already intended to provide loose coupling between the HTTP server and the storage implementation, and the storeTimeout (which determines how long the server is prepared to wait for the store to return a value) seems more a a concern of the HTTP server than the storage service. Having said that, I'm happy to look at what you have in mind.

**Comment by amdw** [comment]
As mentioned elsewhere, I think we want to keep the `Server` type in some form, because it represents the HTTP request handling logic.

Moving all this to a separate package is now done in #47.

I'm therefore closing this issue. If you think I've missed something important, please let me know. Thanks!
